export const SIGN_UP_USER = 'SIGN_UP_USER';
export const LOG_IN_USER = 'LOG_IN_USER';

export const SELECT_PROFILE_PIC = 'SELECT_PROFILE_PIC';
export const PROFILE_PIC_IS_SELECTED = 'PROFILE_PIC_IS_SELECTED';
export const POST_PROFILE_PIC_SUCCESS = 'POST_PROFILE_PIC_SUCCESS';
export const NO_PROFILE_PIC_SELECTED = 'NO_PROFILE_PIC_SELECTED';
export const CAPTURE_PROFILE_PIC = 'CAPTURE_PROFILE_PIC';
export const SET_PROFILE_PIC = 'SET_PROFILE_PIC';
